name: Ohe-testing

on:
  push:
    branches: 
      - ohe-forV1.1
    paths:
      - 'sushi-config.yaml'
      - 'input/**'
  pull_request:
    branches: [ ohe-forV1.1 ]
    
jobs:
  turn:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    steps:
    - uses: actions/checkout@v2

    - name: Setup npm
      uses: actions/setup-node@v2
      with: 
        check-latest: true

    - name: Setup Sushi
      run: |
        sudo npm install -g fsh-sushi
    - name: Install Jekyll
      run: |
        sudo apt-get install jekyll
        
    - name: Download IG Publisher
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: HL7/fhir-ig-publisher
        tag: 'latest'
        path: .
        file: publisher.jar
   
    - name: Run IG Publisher
      run: | 
        mkdir input-cache
        mv publisher.jar ./input-cache/publisher.jar
        unset DISPLAY
        java -Djava.awt.headless=true -jar ./input-cache/publisher.jar -ig ig.ini
    - name: Deploy Implementation Guide
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: kazuhiko-ohe/jp-core-develop
        publish_branch: ohe-forV1.1-pages
        publish_dir: ./output
    - name: ssh key generate
      run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TO_JPFHIR }}
    - name: ssh key echo
      run: echo "$SSH_PRIVATE_KEY2"
      env:
          SSH_PRIVATE_KEY2: ${{ secrets.SSH_PRIVATE_KEY_TO_JPFHIR }}
    - name: rsync remote-site-deploy
      run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 8022" --delete ./output/ ./fsh-generated/ r2217734@www41.onamae.ne.jp:/home/r2217734/public_html/jpfhir.jp/work/ --exclude .htaccess
